
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: identity-route
          uri: lb://identity-service
          predicates:
            - Path=/identityService/**
        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/notificationService/**

eureka:
  client:
    service-url:
      defaultZone: http://3.148.117.109:8761/eureka/