management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

server:
  port: 8081

spring:
  application:
    name: identity-service
  mvc:
    problemdetails:
      enabled: true  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/